#!/bin/sh
set -e
# Automatically added by dh_systemd_start/13.3.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.3.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'alarm_authlog.service' 'alarm_authlog.timer' 'alarm_cleanup.service' 'alarm_cleanup.timer' 'alarmd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'alarm_authlog.service' 'alarm_authlog.timer' 'alarm_cleanup.service' 'alarm_cleanup.timer' 'alarmd.service' >/dev/null || true
		deb-systemd-helper unmask 'alarm_authlog.service' 'alarm_authlog.timer' 'alarm_cleanup.service' 'alarm_cleanup.timer' 'alarmd.service' >/dev/null || true
	fi
fi
# End automatically added section
